test6

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,13 +20,20 @@ jobs:
           passphrase: ${{ secrets.SSH_PASSPHRASE }}  # 秘密鍵のパスフレーズを指定
           script: |
             echo "Moving to the deployment directory..."
-            cd ${{ secrets.SERVER_DEPLOY_DIR }}
-            echo "Current working directory:"
+            if [ -d ${{ secrets.SERVER_DEPLOY_DIR }} ]; then
+              cd ${{ secrets.SERVER_DEPLOY_DIR }}
+              echo "Current working directory:"
             pwd
-            # git status
-            # git checkout main
-            # git branch -a
-            # git remote -v
-            echo "Switching to main branch and pulling latest changes..."
+            else
+              echo "Error: Deployment directory does not exist."
+              exit 1
+            fi
+
+            if [ -d .git ]; then
+              echo "This is a Git repository. Switching to main branch and pulling latest changes..."
             git switch main
             git pull origin main
+            else
+            echo "Error: This is not a Git repository."
+            exit 1
+            fi
